type SearchResult={title?:string;url?:string;content?:string;description?:string;thumbnail?:string;img_src?:string};
export type LiveCard={id:string;category:string;entityId:string;displayOrder:number;notes:string;entityData:Record<string,unknown>&{id:string}};
const SEARCH='https://orange-brook-a2ac.marvaseater.workers.dev/search';
const GPT='https://infinity-rogers.marvaseater.workers.dev/v1/chat';
async function search(query:string,category='general'){
  const url=new URL(SEARCH); url.search=new URLSearchParams({q:query,format:'json',categories:category,safesearch:'1'}).toString();
  const response=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(8000)});
  if(!response.ok)throw new Error('search unavailable');
  const body=await response.json() as {results?:SearchResult[]};
  return (body.results||[]).filter(item=>item.url&&item.title).slice(0,5);
}
function best(results:SearchResult[],prefer?:RegExp){return results.find(x=>prefer?.test(x.url||''))||results[0]}
function clean(value?:string){return String(value||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
async function storyline(cards:Array<Record<string,unknown>>){
  const input='Write one concise connecting storyline for this Alien Coin asset bundle. Explain why the movie, song, poem, tree and recipe fit together. Return plain text only.';
  const response=await fetch(GPT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({input,context:{application:'Alien Coin',task:'mint-bundle-storyline',verified_context:{cards}}}),signal:AbortSignal.timeout(18000),cache:'no-store'});
  if(!response.ok)throw new Error('GPT unavailable');
  const body=await response.json() as {output_text?:string;output?:string};
  return clean(body.output_text||body.output);
}
export async function buildLiveAssetCards(profile:{zone?:string;ingredients?:string}={}):Promise<LiveCard[]>{
  const zone=clean(profile.zone)||'Iowa zone 5';
  const ingredients=clean(profile.ingredients)||'seasonal pantry ingredients';
  const jobs=[
    ['video','full movie classic film site:youtube.com/watch','videos'],
    ['song','famous song official audio site:youtube.com/watch','videos'],
    ['poem','classic poem Poetry Foundation public domain','general'],
    ['tree','native tree '+zone+' USDA extension','general'],
    ['meal','recipe '+ingredients,'general'],
    ['coupon','coupon local offer '+zone,'general'],
    ['collectible','interesting collectible art mineral coin museum','images'],
  ] as const;
  const settled=await Promise.all(jobs.map(async([category,q,kind])=>{
    try{return {category,result:best(await search(q,kind),category==='video'||category==='song'?/youtube\.com|youtu\.be/i:undefined)}}
    catch{return {category,result:undefined}}
  }));
  const cards:LiveCard[]=settled.filter(x=>x.result).map((entry,index)=>{
    const item=entry.result!; const url=item.url!; const summary=clean(item.content||item.description);
    return {id:'live:'+entry.category+':'+index,category:entry.category,entityId:url,displayOrder:20+index,notes:'Live Infinity 5 search selection',entityData:{id:url,title:clean(item.title),summary,url,sourceUrl:url,youtubeUrl:/youtube\.com|youtu\.be/i.test(url)?url:undefined,imageUrl:item.img_src||item.thumbnail,zone:entry.category==='tree'?zone:undefined,ingredients:entry.category==='meal'?ingredients:undefined}};
  });
  try{const story=await storyline(cards.map(x=>x.entityData)); if(story)cards.push({id:'live:story',category:'story',entityId:'gpt:alien-coin-story',displayOrder:40,notes:'Generated by the connected Infinity GPT route',entityData:{id:'gpt:alien-coin-story',title:'Your Alien Coin Story',summary:story,sourceUrl:null}})}catch{}
  return cards;
}
